import { Dish } from "../models/dish";

export const dishes: Dish[] = [
    { name: 'Diablo',             categoryId: 1, weight: '360g',  categoryName: 'Pizza',     price: 10799,   img:"assets/images/pizza/Diablo.png",            link: 'diablo',             sale: true,     mostPopular: true,   description: 'Bacon, salami, prosciutto koto, fresh tomatoes, repperoni hot pepper, mozzarella cheese, chili sauce, marinara sauce' },
    { name: '4-Cheese',           categoryId: 1, weight: '230g',  categoryName: 'Pizza',     price: 9859,    img:"assets/images/pizza/4-Cheese.png",          link: "4-cheese",           sale: false,    mostPopular: false,  description: 'Gouda cheese, Mozzarella cheese, Gorgonzola cheese, Parmesan cheese, cream sauce' },
    { name: 'Americano De Luxe',  categoryId: 1, weight: '410g',  categoryName: 'Pizza',     price: 14959,   img:"assets/images/pizza/AmericanoDeLuxe.png",   link: "americano-deluxe",   sale: true,     mostPopular: false,  description: 'Prosciutto coto di pollo, prosciutto coto di manzo, smoked chicken fillet, bacon, salami, fresh tomatoes, mozzarella cheese, BBQ sauce (on a thick crust)' },
    { name: 'Italliano De Luxe',  categoryId: 1, weight: '410g',  categoryName: 'Pizza',     price: 13919,   img:"assets/images/pizza/ItallianoDeLuxe.png",   link: "italliano-deluxe",   sale: false,    mostPopular: false,  description: 'Prosciutto coto, bacon, prosciutto coto di manzo, hunting sausages, salami, fresh tomatoes, mozzarella cheese, marinara sauce (on a lush crust)' },
    { name: 'Margarita',          categoryId: 1, weight: '290g',  categoryName: 'Pizza',     price: 11699,   img:"assets/images/pizza/Margarita.png",         link: "margarita",          sale: false,    mostPopular: false,  description: 'Cherry tomatoes, pesto sauce, marinara sauce, mozzarella cheese and soft mozzarella' },
    { name: 'Peperoni',           categoryId: 1, weight: '360g',  categoryName: 'Pizza',     price: 11899,   img:"assets/images/pizza/Peperoni.png",          link: "peperoni",           sale: false,    mostPopular: false,  description: 'Bacon, salami, prosciutto, fresh tomatoes, mushrooms, repperoni hot pepper, mozzarella cheese, marinara sauce' },
    { name: 'Casablanka',         categoryId: 1, weight: '380g',  categoryName: 'Pizza',     price: 12949,   img:"assets/images/pizza/Casablanka.png",        link: "casablanka",         sale: false,    mostPopular: false,  description: '4 types of meat: prosciutto cotto di Manzo, prosciutto cotto, smoked chicken fillet, bacon, mushrooms, fresh tomatoes, sweet pepper, mozzarella cheese, marinara sauce' },
    { name: 'Fokacha',            categoryId: 1, weight: '155g',  categoryName: 'Pizza',     price: 3699,    img:"assets/images/pizza/Fokacha.png",           link: "fokacha",            sale: false,    mostPopular: false,  description: 'Traditional Italian cake with spicy herbs and Parmesan cheese' },
    { name: 'Carbonara',          categoryId: 1, weight: '340g',  categoryName: 'Pizza',     price: 12579,   img:"assets/images/pizza/Carbonara.png",         link: "carbonara",          sale: false,    mostPopular: false,  description: 'Prosciutto cotto, bacon, quail eggs, pickled onions, fresh tomatoes, mozzarella cheese, cream sauce' },
    { name: 'San Siro',           categoryId: 1, weight: '370g',  categoryName: 'Pizza',     price: 11799,   img:"assets/images/pizza/SanSiro.png",           link: "san-siro",           sale: false,    mostPopular: false,  description: 'Prosciutto cotto, hunting sausages, smoked chicken fillet, mushrooms, pickled onions, fresh tomatoes, mozzarella cheese, marinara sauce' },
    { name: 'Filadelfia',         categoryId: 1, weight: '360g',  categoryName: 'Pizza',     price: 14759,   img:"assets/images/pizza/FiladelfiaP.png",       link: "filadelfia-p",       sale: true,     mostPopular: false,  description: 'Roast neck, salami, olives, mushrooms, Philadelphia cheese, gorgonzola cheese, mozzarella cheese, marinara sauce' },
    { name: 'Bavarian',           categoryId: 1, weight: '360g',  categoryName: 'Pizza',     price: 11899,   img:"assets/images/pizza/Bavarian.png",          link: "bavarian",           sale: false,    mostPopular: false,  description: '4 types of sausages: sausage, Frankfurter, Munich and homemade, mushrooms, pickled onions, mozzarella cheese, spicy tomato sauce' },

    { name: 'Sake Unagi Roll',    categoryId: 2, weight: '329g',  categoryName: 'Sushi',     price: 32899,   img:"assets/images/sushi/SakeUnagiRoll.png",     link: "skae-unagi-roll",    sale: true,     mostPopular: false,  description: 'Salmon, eel, cucumber, Philadelphia cheese, tobiko caviar' },
    { name: 'Green Dragon',       categoryId: 2, weight: '290g',  categoryName: 'Sushi',     price: 27579,   img:"assets/images/sushi/GreenDragon.png",       link: "green-dragon",       sale: false,    mostPopular: false,  description: 'Eel, avocado, cucumber, tobiko caviar, Japanese mayonnaise, tomago-yaki, unagi sauce, sesame' },
    { name: 'Black Dragon',       categoryId: 2, weight: '320g',  categoryName: 'Sushi',     price: 35999,   img:"assets/images/sushi/BlackDragon.png",       link: "black-dragon",       sale: false,    mostPopular: false,  description: 'Eel, salmon, Philadelphia cheese, tamago-yaki, unagi sauce, sesame, rice, nori: served with wasabi, ginger and soy sauce' },
    { name: 'Red Dragon',         categoryId: 2, weight: '300g',  categoryName: 'Sushi',     price: 37919,   img:"assets/images/sushi/RedDragon.png",         link: "red-dragon",         sale: true,     mostPopular: false,  description: 'Salmon, eel, avocado, cucumber, Japanese mayonnaise, tobiko caviar, rice, nori: served with wasabi, ginger and soy sauce' },
    { name: 'Filadelfia',         categoryId: 2, weight: '290g',  categoryName: 'Sushi',     price: 28519,   img:"assets/images/sushi/FiladelfiaS.png",       link: "filadelfia-s",       sale: false,    mostPopular: true,   description: 'Salmon, avocado, Philadelphia cheese, tobiko caviar' },
    { name: 'Filadelfia Lite',    categoryId: 2, weight: '250g',  categoryName: 'Sushi',     price: 22959,   img:"assets/images/sushi/FiladelfiaLite.png",    link: "filadelfia-lite",    sale: false,    mostPopular: false,  description: 'Salmon, cucumber, Philadelphia cheese' },
    { name: 'Filadelfia Kunsei',  categoryId: 2, weight: '280g',  categoryName: 'Sushi',     price: 32599,   img:"assets/images/sushi/FiladelfiaKunsei.png",  link: "filadelfia-kunsei",  sale: false,    mostPopular: false,  description: 'Smoked salmon, avocado, Philadelphia cheese' },
    { name: 'Cheff Grill Roll',   categoryId: 2, weight: '280g',  categoryName: 'Sushi',     price: 28979,   img:"assets/images/sushi/CheffGrillRoll.png",    link: "cheff-grill-roll",   sale: false,    mostPopular: false,  description: 'Tiger shrimp, salmon fillet, avocado, Philadelphia cheese' },
    { name: 'Grill Roll',         categoryId: 2, weight: '290g',  categoryName: 'Sushi',     price: 26599,   img:"assets/images/sushi/GrillRoll.png",         link: "grill-roll",         sale: true,     mostPopular: false,  description: 'Salmon, Philadelphia cheese, pear, tobiko caviar, unagi sauce' },
    { name: 'Hot Crab',           categoryId: 2, weight: '280g',  categoryName: 'Sushi',     price: 17859,   img:"assets/images/sushi/HotCrab.png",           link: "hot-crab",           sale: false,    mostPopular: false,  description: 'Snow crab, fresh cucumber, tobiko caviar, Philadelphia cheese, mozzarella cheese, Japanese mayonnaise, sesame' },

    { name: 'Breakfast',          categoryId: 3, weight: '250g',  categoryName: 'Pancakes',  price: 6719,    img:"assets/images/pancakes/Breakfast.png",      link: "breakfast",          sale: false,    mostPopular: false,  description: 'Mozzarella, mushrooms, ham, egg and mixed salad' },
    { name: 'Caesar',             categoryId: 3, weight: '210g',  categoryName: 'Pancakes',  price: 7559,    img:"assets/images/pancakes/Caesar.png",         link: "caesar",             sale: false,    mostPopular: false,  description: 'Chicken fillet, mixed salad, mozzarella, tomatoes, Caesar and balsamic sauces' },
    { name: 'Caprichoza',         categoryId: 3, weight: '210g',  categoryName: 'Pancakes',  price: 8849,    img:"assets/images/pancakes/Caprichoza.png",     link: "caprichoza",         sale: false,    mostPopular: false,  description: 'Mozzarella, mushrooms, salami, salad mix, artichokes, prosciutto, carrots, tomatoes' },
    { name: 'Diabola',            categoryId: 3, weight: '170g',  categoryName: 'Pancakes',  price: 7599,    img:"assets/images/pancakes/Diabola.png",        link: "diabola",            sale: false,    mostPopular: false,  description: 'Mozzarella, pepperoni salami, chili pepper, mixed salad, olives, bell pepper, balsamic sauce' },
    { name: 'Sorento',            categoryId: 3, weight: '185g',  categoryName: 'Pancakes',  price: 9699,    img:"assets/images/pancakes/Sorento.png",        link: "sorento",            sale: false,    mostPopular: false,  description: 'Salmon, feta, mixed salad, cucumber, Italian dressing' },

    { name: 'Orange Fresh',       categoryId: 4, weight: '500ml',  categoryName: 'Drinks',   price: 3999,    img:"assets/images/drinks/OrangeFresh.png",      link: "orange-fresh",       sale: false,    mostPopular: false,  description: '' },
    { name: 'Multifruit Fresh',   categoryId: 4, weight: '500ml',  categoryName: 'Drinks',   price: 3999,    img:"assets/images/drinks/MultifruitFresh.png",  link: "multifruit-fresh",   sale: false,    mostPopular: false,  description: '' },
    { name: 'Lemonade',           categoryId: 4, weight: '500ml',  categoryName: 'Drinks',   price: 3999,    img:"assets/images/drinks/Lemonade.png",         link: "lemonade",           sale: false,    mostPopular: false,  description: '' },
    { name: 'Coca Cola',          categoryId: 4, weight: '500ml',  categoryName: 'Drinks',   price: 4999,    img:"assets/images/drinks/CocaCola.png",         link: "coca-cola",          sale: false,    mostPopular: false,  description: '' },
    { name: 'Bud Light',          categoryId: 4, weight: '500ml',  categoryName: 'Drinks',   price: 5999,    img:"assets/images/drinks/BudLight.png",         link: "bud-light",          sale: false,    mostPopular: true,   description: '' },
  ];